import { StyleSheet, Platform } from 'react-native';

// ─── Palette (same as AboutScreen, DashboardScreen, UsersScreen, ForumScreen) ─
const C = {
  forest:     '#2d5016',
  sage:       '#3d6b22',
  sageMed:    '#5a8c35',
  sagePale:   '#d4ecb8',
  sageMid:    '#b0d890',
  sageTint:   '#e4f5d0',
  inkSoft:    '#2e4420',
  inkFaint:   '#6a8450',
  mist:       '#dff0cc',
  fog:        '#cce8b0',
  bg:         '#cce8a8',
  borderSoft: '#cce0a8',
  borderMid:  '#aed090',
  cardBg:     '#f0f9e4',
  white:      '#ffffff',
};

export const styles = StyleSheet.create({

  // ── Container ─────────────────────────────────────────────────────────────
  container: {
    flex: 1,
    backgroundColor: C.bg,
  },
  loadingContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    gap: 12,
  },
  loadingText: {
    marginTop: 4,
    fontSize: 13,
    fontWeight: '600',
    color: C.inkFaint,
    letterSpacing: 0.3,
  },
  scrollContent: {
    paddingBottom: 40,
    gap: 0,
  },

  // ── Header ────────────────────────────────────────────────────────────────
  header: {
    backgroundColor: C.forest,
    paddingTop: 52,
    paddingBottom: 20,
    paddingHorizontal: 20,
    flexDirection: 'row',
    alignItems: 'flex-end',
    justifyContent: 'space-between',
    borderBottomWidth: 2,
    borderBottomColor: C.borderMid,
    ...Platform.select({
      ios:     { shadowColor: C.forest, shadowOffset: { width: 0, height: 4 }, shadowOpacity: 0.18, shadowRadius: 12 },
      android: { elevation: 6 },
    }),
  },
  headerLeft: {
    flex: 1,
  },
  headerEyebrow: {
    fontSize: 10,
    fontWeight: '700',
    color: C.sageMid,
    letterSpacing: 2.5,
    textTransform: 'uppercase',
    marginBottom: 2,
  },
  headerTitle: {
    fontSize: 28,
    fontWeight: '900',
    color: C.white,
    letterSpacing: -0.6,
  },
  headerActions: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  pdfBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 5,
    paddingHorizontal: 13,
    paddingVertical: 8,
    borderRadius: 10,
    borderWidth: 1.5,
    borderColor: 'rgba(255,255,255,0.35)',
    backgroundColor: 'rgba(255,255,255,0.08)',
  },
  pdfBtnText: {
    fontSize: 12,
    fontWeight: '700',
    color: C.white,
    letterSpacing: 0.2,
  },
  refreshBtn: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: 'rgba(255,255,255,0.12)',
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1.5,
    borderColor: 'rgba(255,255,255,0.25)',
  },

  // ── Period Selector ───────────────────────────────────────────────────────
  periodSelector: {
    flexDirection: 'row',
    backgroundColor: C.cardBg,
    borderRadius: 14,
    padding: 4,
    marginHorizontal: 16,
    marginTop: -16,
    marginBottom: 20,
    borderWidth: 1.5,
    borderColor: C.borderSoft,
    ...Platform.select({
      ios:     { shadowColor: C.forest, shadowOffset: { width: 0, height: 4 }, shadowOpacity: 0.12, shadowRadius: 12 },
      android: { elevation: 6 },
      web:     { boxShadow: '0 4px 14px rgba(26,58,5,0.11)' } as any,
    }),
  },
  periodButton: {
    flex: 1,
    paddingVertical: 9,
    alignItems: 'center',
    borderRadius: 10,
  },
  periodButtonActive: {
    backgroundColor: C.forest,
  },
  periodText: {
    fontSize: 12,
    fontWeight: '600',
    color: C.inkFaint,
    letterSpacing: 0.1,
  },
  periodTextActive: {
    color: C.white,
    fontWeight: '700',
  },

  // ── Section ───────────────────────────────────────────────────────────────
  section: {
    marginBottom: 12,
    padding: 16,
    backgroundColor: C.cardBg,
    borderBottomWidth: 1.5,
    borderBottomColor: C.borderSoft,
  },
  sectionTitle: {
    fontSize: 15,
    fontWeight: '800',
    color: C.inkSoft,
    marginBottom: 14,
    letterSpacing: -0.2,
  },

  // ── Insight Cards ─────────────────────────────────────────────────────────
  insightsGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 12,
  },
  insightCard: {
    flex: 1,
    minWidth: '47%',
    backgroundColor: C.mist,
    padding: 14,
    borderRadius: 14,
    borderWidth: 1.5,
    borderColor: C.borderSoft,
    ...Platform.select({
      ios:     { shadowColor: C.forest, shadowOffset: { width: 0, height: 2 }, shadowOpacity: 0.08, shadowRadius: 8 },
      android: { elevation: 3 },
      web:     { boxShadow: '0 2px 10px rgba(26,58,5,0.09)' } as any,
    }),
    alignItems: 'center',
  },
  insightIcon: {
    width: 44,
    height: 44,
    borderRadius: 22,
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 10,
    borderWidth: 1.5,
    borderColor: C.borderMid,
  },
  insightValue: {
    fontSize: 22,
    fontWeight: '900',
    marginBottom: 3,
    letterSpacing: -0.5,
  },
  insightTitle: {
    fontSize: 11,
    fontWeight: '700',
    color: C.inkSoft,
    marginBottom: 2,
    textAlign: 'center',
    letterSpacing: 0.1,
  },
  insightDescription: {
    fontSize: 11,
    color: C.inkFaint,
    textAlign: 'center',
  },

  // ── Chart Card ────────────────────────────────────────────────────────────
  chartCard: {
    backgroundColor: C.cardBg,
    padding: 16,
    marginBottom: 12,
    borderBottomWidth: 1.5,
    borderBottomColor: C.borderSoft,
    overflow: 'hidden',
  },
  chartHeader: {
    marginBottom: 8,
  },
  chartTitle: {
    fontSize: 15,
    fontWeight: '800',
    color: C.inkSoft,
    marginBottom: 2,
    letterSpacing: -0.2,
  },
  chartSubtitle: {
    fontSize: 11,
    color: C.inkFaint,
    letterSpacing: 0.1,
  },
  chart: {
    marginVertical: 8,
    borderRadius: 12,
  },

  // ── Legend ────────────────────────────────────────────────────────────────
  legendRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 12,
    marginBottom: 8,
  },
  legendItem: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  legendDot: {
    width: 9,
    height: 9,
    borderRadius: 5,
  },
  legendLabel: {
    fontSize: 11,
    color: C.inkFaint,
    fontWeight: '600',
    letterSpacing: 0.1,
  },

  // ── Analytics List ────────────────────────────────────────────────────────
  analyticsCard: {
    backgroundColor: C.cardBg,
    padding: 16,
    marginBottom: 12,
    borderBottomWidth: 1.5,
    borderBottomColor: C.borderSoft,
  },
  analyticsItem: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: C.borderSoft,
  },
  analyticsIcon: {
    width: 42,
    height: 42,
    borderRadius: 12,
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 12,
    borderWidth: 1.5,
    borderColor: C.borderMid,
  },
  analyticsContent: {
    flex: 1,
  },
  analyticsLabel: {
    fontSize: 12,
    fontWeight: '700',
    color: C.inkSoft,
    marginBottom: 2,
    letterSpacing: 0.1,
  },
  analyticsValue: {
    fontSize: 17,
    fontWeight: '900',
    letterSpacing: -0.3,
  },

  // ── History Table ─────────────────────────────────────────────────────────
  tableCard: {
    backgroundColor: C.cardBg,
    borderRadius: 14,
    padding: 16,
    marginHorizontal: 16,
    marginBottom: 20,
    borderWidth: 1.5,
    borderColor: C.borderMid,
    ...Platform.select({
      ios:     { shadowColor: C.forest, shadowOffset: { width: 0, height: 2 }, shadowOpacity: 0.08, shadowRadius: 8 },
      android: { elevation: 3 },
      web:     { boxShadow: '0 2px 10px rgba(26,58,5,0.09)' } as any,
    }),
  },
  tableHeaderRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 12,
  },
  tableCount: {
    fontSize: 11,
    color: C.inkFaint,
    fontWeight: '700',
    backgroundColor: C.mist,
    paddingHorizontal: 10,
    paddingVertical: 3,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: C.borderSoft,
  },
  tableHead: {
    flexDirection: 'row',
    backgroundColor: C.forest,
    borderRadius: 10,
    paddingVertical: 10,
    paddingHorizontal: 4,
    marginBottom: 2,
  },
  tableHeadCell: {
    width: 100,
    fontSize: 10,
    fontWeight: '700',
    color: C.sageMid,
    paddingHorizontal: 8,
    textTransform: 'uppercase',
    letterSpacing: 1,
  },
  tableRow: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 10,
    paddingHorizontal: 4,
    borderBottomWidth: 1,
    borderBottomColor: C.borderSoft,
    backgroundColor: C.cardBg,
  },
  tableRowAlt: {
    backgroundColor: C.mist,
  },
  tableCell: {
    width: 100,
    fontSize: 12,
    color: C.inkSoft,
    paddingHorizontal: 8,
    fontWeight: '500',
  },
  typeBadge: {
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: 8,
    alignSelf: 'flex-start',
    borderWidth: 1,
    borderColor: C.borderSoft,
  },
  typeBadgeText: {
    fontSize: 10,
    fontWeight: '700',
    letterSpacing: 0.3,
  },
  statusBadge: {
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: 8,
    alignSelf: 'flex-start',
  },
  statusText: {
    fontSize: 10,
    fontWeight: '700',
    letterSpacing: 0.3,
  },

  // ── History Rows (card-based, full-width) ─────────────────────────────────
  historyRow: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 10,
    paddingHorizontal: 16,
    borderBottomWidth: 1,
    borderBottomColor: C.borderSoft,
    backgroundColor: C.cardBg,
    gap: 12,
  },
  historyRowAlt: {
    backgroundColor: C.mist,
  },
  historyThumbWrap: {
    width: 50,
    height: 50,
    borderRadius: 10,
    overflow: 'hidden',
    flexShrink: 0,
    borderWidth: 1.5,
    borderColor: C.borderMid,
  },
  historyThumb: {
    width: 50,
    height: 50,
    borderRadius: 10,
    resizeMode: 'cover',
  },
  historyThumbPlaceholder: {
    width: 50,
    height: 50,
    borderRadius: 10,
    justifyContent: 'center',
    alignItems: 'center',
  },
  historyContent: {
    flex: 1,
    gap: 3,
    minWidth: 0,
  },
  historyBadgeRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    flexWrap: 'wrap',
  },
  historyConfidence: {
    fontSize: 10,
    fontWeight: '700',
    color: C.sage,
    backgroundColor: C.sageTint,
    paddingHorizontal: 6,
    paddingVertical: 2,
    borderRadius: 6,
    borderWidth: 1,
    borderColor: C.borderMid,
  },
  historyResult: {
    fontSize: 13,
    fontWeight: '700',
    color: C.inkSoft,
  },
  historyMeta: {
    fontSize: 11,
    color: C.inkFaint,
    fontWeight: '500',
  },

  // ── Pagination ────────────────────────────────────────────────────────────
  pagination: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: 12,
    paddingHorizontal: 16,
    gap: 6,
  },
  pageBtn: {
    width: 34,
    height: 34,
    borderRadius: 10,
    backgroundColor: C.cardBg,
    borderWidth: 1.5,
    borderColor: C.borderMid,
    justifyContent: 'center',
    alignItems: 'center',
  },
  pageBtnDisabled: {
    backgroundColor: C.mist,
    borderColor: C.borderSoft,
  },
  pageNumberBtn: {
    width: 34,
    height: 34,
    borderRadius: 10,
    backgroundColor: C.cardBg,
    borderWidth: 1.5,
    borderColor: C.borderMid,
    justifyContent: 'center',
    alignItems: 'center',
  },
  pageNumberBtnActive: {
    backgroundColor: C.forest,
    borderColor: C.forest,
  },
  pageNumberText: {
    fontSize: 12,
    fontWeight: '700',
    color: C.sage,
  },
  pageNumberTextActive: {
    color: C.white,
  },

  // ── Stats row (Market Sales) ──────────────────────────────────────────────
  statsRow: {
    flexDirection: 'row',
    gap: 12,
    marginBottom: 12,
  },
  statItem: {
    flex: 1,
    backgroundColor: C.mist,
    borderRadius: 10,
    padding: 10,
    borderWidth: 1.5,
    borderColor: C.borderSoft,
  },
  statLabel: {
    fontSize: 9,
    color: C.inkFaint,
    fontWeight: '700',
    textTransform: 'uppercase',
    letterSpacing: 0.8,
    marginBottom: 3,
  },
  statValue: {
    fontSize: 15,
    fontWeight: '900',
    color: C.inkSoft,
    letterSpacing: -0.3,
  },

  // ── Export Modal ──────────────────────────────────────────────────────────
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(26,58,5,0.5)',
    justifyContent: 'flex-end',
  },
  modalContent: {
    backgroundColor: C.cardBg,
    borderTopLeftRadius: 28,
    borderTopRightRadius: 28,
    paddingHorizontal: 20,
    paddingBottom: 32,
    maxHeight: '80%',
    borderTopWidth: 2,
    borderColor: C.borderMid,
  },
  modalHandle: {
    width: 38,
    height: 4,
    borderRadius: 2,
    backgroundColor: C.borderMid,
    alignSelf: 'center',
    marginTop: 12,
    marginBottom: 4,
  },
  modalHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingVertical: 14,
    borderBottomWidth: 1.5,
    borderBottomColor: C.borderSoft,
    marginBottom: 16,
  },
  modalTitle: {
    fontSize: 17,
    fontWeight: '900',
    color: C.inkSoft,
    letterSpacing: -0.3,
  },
  modalCloseBtn: {
    width: 34,
    height: 34,
    borderRadius: 17,
    backgroundColor: C.mist,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1.5,
    borderColor: C.borderMid,
  },
  modalSubtitle: {
    fontSize: 12,
    color: C.inkFaint,
    marginBottom: 14,
    fontWeight: '500',
    letterSpacing: 0.1,
  },
  checkboxContainer: {
    gap: 6,
    marginBottom: 20,
  },
  checkboxRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    paddingVertical: 12,
    paddingHorizontal: 14,
    borderRadius: 12,
    borderWidth: 1.5,
    borderColor: C.borderSoft,
    backgroundColor: C.mist,
  },
  checkboxRowActive: {
    backgroundColor: C.sageTint,
    borderColor: C.sage,
  },
  checkboxLabel: {
    fontSize: 13,
    fontWeight: '700',
    color: C.inkSoft,
    flex: 1,
    letterSpacing: 0.1,
  },
  checkboxDesc: {
    fontSize: 11,
    color: C.inkFaint,
  },
  selectAllRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 10,
  },
  selectAllBtn: {
    fontSize: 12,
    fontWeight: '700',
    color: C.sage,
  },
  modalActions: {
    flexDirection: 'row',
    gap: 12,
  },
  modalButton: {
    flex: 1,
    paddingVertical: 13,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
    flexDirection: 'row',
    gap: 6,
  },
  cancelButton: {
    backgroundColor: C.mist,
    borderWidth: 1.5,
    borderColor: C.borderMid,
  },
  cancelButtonText: {
    fontSize: 13,
    fontWeight: '700',
    color: C.inkFaint,
  },
  confirmButton: {
    flex: 2,
    backgroundColor: C.forest,
    ...Platform.select({
      ios:     { shadowColor: C.forest, shadowOffset: { width: 0, height: 4 }, shadowOpacity: 0.28, shadowRadius: 10 },
      android: { elevation: 5 },
    }),
  },
  confirmButtonText: {
    fontSize: 13,
    fontWeight: '800',
    color: C.white,
    letterSpacing: 0.2,
  },

  // ── Export Button (scroll-bottom fallback) ────────────────────────────────
  exportButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: C.forest,
    marginHorizontal: 16,
    padding: 15,
    borderRadius: 14,
    gap: 8,
    ...Platform.select({
      ios:     { shadowColor: C.forest, shadowOffset: { width: 0, height: 4 }, shadowOpacity: 0.28, shadowRadius: 10 },
      android: { elevation: 5 },
    }),
  },
  exportButtonText: {
    fontSize: 14,
    fontWeight: '800',
    color: C.white,
    letterSpacing: 0.2,
  },
});