import { StyleSheet, Platform } from 'react-native';

// ─── Palette (same as AboutScreen, DashboardScreen, UsersScreen & AdminNavigator) ─
const C = {
  forest:     '#2d5016',
  sage:       '#3d6b22',
  sageMed:    '#5a8c35',
  sagePale:   '#d4ecb8',
  sageMid:    '#b0d890',
  sageTint:   '#e4f5d0',
  inkSoft:    '#2e4420',
  inkFaint:   '#6a8450',
  mist:       '#dff0cc',
  fog:        '#cce8b0',
  bg:         '#cce8a8',
  borderSoft: '#cce0a8',
  borderMid:  '#aed090',
  cardBg:     '#f0f9e4',
  white:      '#ffffff',

  // Semantic accents (kept from original)
  red:        '#ef4444',
  redBg:      '#FEF2F2',
  redBorder:  '#fca5a5',
  green:      '#10b981',
  greenBg:    '#ECFDF5',
  greenBorder:'#6ee7b7',
};

export const styles = StyleSheet.create({

  // ── Container ─────────────────────────────────────────────────────────────
  container: {
    flex: 1,
    backgroundColor: C.bg,
  },
  loadingContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    gap: 12,
  },
  loadingText: {
    marginTop: 4,
    fontSize: 13,
    fontWeight: '600',
    color: C.inkFaint,
    letterSpacing: 0.3,
  },
  scrollContent: {
    paddingBottom: 40,
  },

  // ── Header ────────────────────────────────────────────────────────────────
  header: {
    backgroundColor: C.forest,
    paddingTop: 52,
    paddingBottom: 20,
    paddingHorizontal: 20,
    flexDirection: 'row',
    alignItems: 'flex-end',
    justifyContent: 'space-between',
    borderBottomWidth: 2,
    borderBottomColor: C.borderMid,
    ...Platform.select({
      ios:     { shadowColor: C.forest, shadowOffset: { width: 0, height: 4 }, shadowOpacity: 0.18, shadowRadius: 12 },
      android: { elevation: 6 },
    }),
  },
  headerLeft: {
    flex: 1,
  },
  headerEyebrow: {
    fontSize: 10,
    fontWeight: '700',
    color: C.sageMid,
    letterSpacing: 2.5,
    textTransform: 'uppercase',
    marginBottom: 2,
  },
  headerTitle: {
    fontSize: 28,
    fontWeight: '900',
    color: C.white,
    letterSpacing: -0.6,
  },
  headerActions: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  pdfBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 5,
    paddingHorizontal: 13,
    paddingVertical: 8,
    borderRadius: 10,
    borderWidth: 1.5,
    borderColor: 'rgba(255,255,255,0.35)',
    backgroundColor: 'rgba(255,255,255,0.08)',
  },
  pdfBtnText: {
    fontSize: 12,
    fontWeight: '700',
    color: C.white,
    letterSpacing: 0.2,
  },
  refreshBtn: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: 'rgba(255,255,255,0.12)',
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1.5,
    borderColor: 'rgba(255,255,255,0.25)',
  },
  toggleBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 5,
    paddingHorizontal: 10,
    paddingVertical: 8,
    borderRadius: 10,
    backgroundColor: 'rgba(255,255,255,0.08)',
    borderWidth: 1.5,
    borderColor: 'rgba(255,255,255,0.2)',
  },
  toggleBtnActive: {
    backgroundColor: 'rgba(255,255,255,0.22)',
    borderColor: 'rgba(255,255,255,0.5)',
  },
  toggleBtnText: {
    fontSize: 12,
    fontWeight: '600',
    color: C.sageMid,
    letterSpacing: 0.2,
  },
  toggleBtnTextActive: {
    color: C.white,
    fontWeight: '700',
  },

  // ── Stats Bar ─────────────────────────────────────────────────────────────
  statsBar: {
    flexDirection: 'row',
    backgroundColor: C.cardBg,
    marginHorizontal: 16,
    marginTop: -16,
    borderRadius: 14,
    paddingVertical: 14,
    paddingHorizontal: 8,
    borderWidth: 1.5,
    borderColor: C.borderSoft,
    ...Platform.select({
      ios:     { shadowColor: C.forest, shadowOffset: { width: 0, height: 4 }, shadowOpacity: 0.12, shadowRadius: 12 },
      android: { elevation: 6 },
      web:     { boxShadow: '0 4px 14px rgba(26,58,5,0.11)' } as any,
    }),
  },
  statItem: {
    flex: 1,
    alignItems: 'center',
    gap: 3,
  },
  statValue: {
    fontSize: 20,
    fontWeight: '900',
    color: C.inkSoft,
    letterSpacing: -0.4,
  },
  statLabel: {
    fontSize: 9,
    color: C.inkFaint,
    fontWeight: '700',
    letterSpacing: 0.5,
    textTransform: 'uppercase',
  },
  statDivider: {
    width: 1,
    backgroundColor: C.borderSoft,
  },

  // ── Search ────────────────────────────────────────────────────────────────
  searchContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: C.cardBg,
    marginHorizontal: 16,
    marginTop: 16,
    borderRadius: 12,
    paddingHorizontal: 14,
    paddingVertical: 10,
    borderWidth: 1.5,
    borderColor: C.borderSoft,
    gap: 8,
    ...Platform.select({
      ios:     { shadowColor: C.forest, shadowOffset: { width: 0, height: 2 }, shadowOpacity: 0.07, shadowRadius: 6 },
      android: { elevation: 2 },
      web:     { boxShadow: '0 2px 8px rgba(26,58,5,0.08)' } as any,
    }),
  },
  searchInput: {
    flex: 1,
    fontSize: 14,
    color: C.inkSoft,
    fontWeight: '500',
    padding: 0,
  },

  // ── Filter Tabs ───────────────────────────────────────────────────────────
  filterScroll: {
    marginTop: 12,
    flexGrow: 0,
    flexShrink: 0,
    maxHeight: 44,
  },
  filterContainer: {
    flexDirection: 'row',
    paddingHorizontal: 16,
    gap: 8,
    alignItems: 'center',
  },
  filterButton: {
    height: 34,
    paddingHorizontal: 14,
    borderRadius: 17,
    backgroundColor: C.cardBg,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1.5,
    borderColor: C.borderMid,
  },
  filterButtonActive: {
    backgroundColor: C.forest,
    borderColor: C.forest,
  },
  filterText: {
    fontSize: 12,
    fontWeight: '600',
    color: C.inkFaint,
    letterSpacing: 0.1,
  },
  filterTextActive: {
    color: C.white,
  },

  // ── Empty State ───────────────────────────────────────────────────────────
  emptyState: {
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 60,
    gap: 8,
  },
  emptyText: {
    marginTop: 8,
    fontSize: 15,
    color: C.inkFaint,
    fontWeight: '600',
  },

  // ── Mobile Card View ──────────────────────────────────────────────────────
  postsList: {
    paddingHorizontal: 16,
    paddingTop: 12,
    gap: 12,
  },
  postCard: {
    backgroundColor: C.cardBg,
    padding: 16,
    borderRadius: 14,
    borderWidth: 1.5,
    borderColor: C.borderSoft,
    ...Platform.select({
      ios:     { shadowColor: C.forest, shadowOffset: { width: 0, height: 2 }, shadowOpacity: 0.08, shadowRadius: 8 },
      android: { elevation: 3 },
      web:     { boxShadow: '0 2px 10px rgba(26,58,5,0.09)' } as any,
    }),
  },
  postHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 10,
  },
  authorImage: {
    width: 38,
    height: 38,
    borderRadius: 19,
    marginRight: 10,
    borderWidth: 1.5,
    borderColor: C.borderMid,
  },
  authorAvatar: {
    width: 38,
    height: 38,
    borderRadius: 19,
    backgroundColor: C.sage,
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 10,
    borderWidth: 1.5,
    borderColor: C.borderMid,
  },
  authorAvatarText: {
    fontSize: 15,
    fontWeight: '700',
    color: C.white,
  },
  postHeaderInfo: {
    flex: 1,
  },
  authorName: {
    fontSize: 13,
    fontWeight: '700',
    color: C.inkSoft,
  },
  postDate: {
    fontSize: 11,
    color: C.inkFaint,
    marginTop: 1,
  },
  postTitle: {
    fontSize: 15,
    fontWeight: '800',
    color: C.inkSoft,
    marginBottom: 6,
    letterSpacing: -0.2,
  },
  postContent: {
    fontSize: 13,
    color: C.inkFaint,
    lineHeight: 19,
    marginBottom: 12,
  },
  postFooter: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 14,
  },
  postStatItem: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
  },
  postStatText: {
    fontSize: 12,
    color: C.inkFaint,
    fontWeight: '600',
  },
  archiveButtonMobile: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    marginLeft: 'auto' as any,
    paddingHorizontal: 10,
    paddingVertical: 5,
    borderRadius: 8,
    backgroundColor: C.redBg,
    borderWidth: 1,
    borderColor: C.redBorder,
  },
  archiveButtonText: {
    fontSize: 11,
    fontWeight: '700',
    color: C.red,
  },
  unarchiveButtonMobile: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    marginLeft: 'auto' as any,
    paddingHorizontal: 10,
    paddingVertical: 5,
    borderRadius: 8,
    backgroundColor: C.greenBg,
    borderWidth: 1,
    borderColor: C.greenBorder,
  },
  unarchiveButtonText: {
    fontSize: 11,
    fontWeight: '700',
    color: C.green,
  },

  // ── Category Badge ────────────────────────────────────────────────────────
  categoryBadge: {
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: 8,
    backgroundColor: C.mist,
    borderWidth: 1,
    borderColor: C.borderSoft,
  },
  categoryText: {
    fontSize: 10,
    fontWeight: '700',
    color: C.sage,
    textTransform: 'uppercase',
    letterSpacing: 0.5,
  },

  // ── Desktop Table View ────────────────────────────────────────────────────
  tableWrapper: {
    marginHorizontal: 16,
    marginTop: 12,
    marginBottom: 16,
    borderRadius: 14,
    overflow: 'hidden',
    borderWidth: 1.5,
    borderColor: C.borderMid,
    backgroundColor: C.cardBg,
    ...Platform.select({
      ios:     { shadowColor: C.forest, shadowOffset: { width: 0, height: 3 }, shadowOpacity: 0.09, shadowRadius: 10 },
      android: { elevation: 3 },
      web:     { boxShadow: '0 2px 12px rgba(26,58,5,0.09)' } as any,
    }),
  },
  tableHeader: {
    flexDirection: 'row',
    backgroundColor: C.forest,
    paddingVertical: 12,
    paddingHorizontal: 8,
    alignItems: 'center',
  },
  tableHeaderText: {
    fontSize: 10,
    fontWeight: '700',
    color: C.sageMid,
    textTransform: 'uppercase',
    letterSpacing: 1.2,
  },
  tableRow: {
    flexDirection: 'row',
    paddingVertical: 12,
    paddingHorizontal: 8,
    borderBottomWidth: 1,
    borderBottomColor: C.borderSoft,
    alignItems: 'center',
    backgroundColor: C.cardBg,
  },
  tableRowEven: {
    backgroundColor: C.mist,
  },
  tableCell: {
    fontSize: 13,
    color: C.inkSoft,
    fontWeight: '500',
  },

  // ── Table column widths ────────────────────────────────────────────────────
  colAuthor: {
    width: 160,
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 4,
  },
  colTitle: {
    flex: 2,
    paddingHorizontal: 8,
  },
  colCategory: {
    width: 110,
    paddingHorizontal: 4,
  },
  colStats: {
    width: 90,
    flexDirection: 'row',
    gap: 10,
    paddingHorizontal: 4,
  },
  colDate: {
    width: 110,
    paddingHorizontal: 4,
  },
  colActions: {
    width: 90,
    flexDirection: 'row',
    gap: 6,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 4,
  },

  // ── Table author cell ─────────────────────────────────────────────────────
  authorImageTable: {
    width: 30,
    height: 30,
    borderRadius: 15,
    marginRight: 8,
    borderWidth: 1.5,
    borderColor: C.borderMid,
  },
  authorAvatarTable: {
    width: 30,
    height: 30,
    borderRadius: 15,
    backgroundColor: C.sage,
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 8,
    borderWidth: 1.5,
    borderColor: C.borderMid,
  },
  authorAvatarTextTable: {
    fontSize: 12,
    fontWeight: '700',
    color: C.white,
  },
  authorNameTable: {
    fontSize: 12,
    fontWeight: '600',
    color: C.inkSoft,
    flex: 1,
  },

  // ── Table action buttons ──────────────────────────────────────────────────
  viewButton: {
    padding: 6,
    borderRadius: 7,
    borderWidth: 1.5,
    borderColor: C.borderMid,
    alignItems: 'center',
    justifyContent: 'center',
  },
  archiveButton: {
    padding: 6,
    borderRadius: 7,
    borderWidth: 1.5,
    borderColor: C.red,
    alignItems: 'center',
    justifyContent: 'center',
  },
  unarchiveButton: {
    padding: 6,
    borderRadius: 7,
    borderWidth: 1.5,
    borderColor: C.green,
    alignItems: 'center',
    justifyContent: 'center',
  },

  // ── Detail Modal ──────────────────────────────────────────────────────────
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(26,58,5,0.5)',
    justifyContent: 'flex-end',
  },
  modalContainer: {
    backgroundColor: C.cardBg,
    borderTopLeftRadius: 28,
    borderTopRightRadius: 28,
    maxHeight: '92%',
    paddingHorizontal: 20,
    paddingBottom: 20,
    borderTopWidth: 2,
    borderColor: C.borderMid,
  },
  modalContainerDesktop: {
    borderRadius: 20,
    maxWidth: 600,
    alignSelf: 'center',
    width: '100%',
    marginVertical: 'auto' as any,
    maxHeight: '90%',
  },
  modalHandle: {
    width: 38,
    height: 4,
    borderRadius: 2,
    backgroundColor: C.borderMid,
    alignSelf: 'center',
    marginTop: 12,
    marginBottom: 4,
  },
  modalHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingVertical: 14,
    borderBottomWidth: 1.5,
    borderBottomColor: C.borderSoft,
    marginBottom: 4,
  },
  modalTitle: {
    fontSize: 17,
    fontWeight: '900',
    color: C.inkSoft,
    letterSpacing: -0.3,
  },
  modalCloseBtn: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: C.mist,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1.5,
    borderColor: C.borderMid,
  },
  modalBody: {
    paddingTop: 4,
  },

  // ── Modal author banner ───────────────────────────────────────────────────
  authorInfoModal: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 16,
    marginBottom: 16,
    padding: 14,
    backgroundColor: C.mist,
    borderRadius: 12,
    borderWidth: 1.5,
    borderColor: C.borderSoft,
    gap: 12,
  },
  authorImageModal: {
    width: 46,
    height: 46,
    borderRadius: 23,
    borderWidth: 1.5,
    borderColor: C.borderMid,
  },
  authorAvatarModal: {
    width: 46,
    height: 46,
    borderRadius: 23,
    backgroundColor: C.sage,
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 1.5,
    borderColor: C.borderMid,
  },
  authorAvatarTextModal: {
    fontSize: 18,
    fontWeight: '700',
    color: C.white,
  },
  authorNameModal: {
    fontSize: 14,
    fontWeight: '800',
    color: C.inkSoft,
    marginBottom: 2,
  },
  postDateModal: {
    fontSize: 12,
    color: C.inkFaint,
  },

  // ── Modal content ─────────────────────────────────────────────────────────
  postTitleModal: {
    fontSize: 19,
    fontWeight: '900',
    color: C.inkSoft,
    marginBottom: 10,
    letterSpacing: -0.4,
  },
  postContentModal: {
    fontSize: 14,
    color: C.inkSoft,
    lineHeight: 22,
    marginBottom: 16,
  },
  imagesContainer: {
    marginBottom: 16,
  },
  postImage: {
    width: 200,
    height: 160,
    borderRadius: 10,
    marginRight: 10,
    borderWidth: 1.5,
    borderColor: C.borderSoft,
  },

  // ── Modal stats row ───────────────────────────────────────────────────────
  statsRowModal: {
    flexDirection: 'row',
    gap: 20,
    marginBottom: 20,
    padding: 14,
    backgroundColor: C.mist,
    borderRadius: 12,
    borderWidth: 1.5,
    borderColor: C.borderSoft,
  },
  statItemModal: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  statTextModal: {
    fontSize: 14,
    fontWeight: '700',
    color: C.inkSoft,
  },

  // ── Archive button in modal ───────────────────────────────────────────────
  archiveButtonModal: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: C.red,
    padding: 14,
    borderRadius: 12,
    gap: 8,
    marginBottom: 8,
  },
  archiveButtonTextModal: {
    fontSize: 14,
    fontWeight: '700',
    color: C.white,
  },
  unarchiveButtonModal: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: C.green,
    padding: 14,
    borderRadius: 12,
    gap: 8,
    marginBottom: 8,
  },
  unarchiveButtonTextModal: {
    fontSize: 14,
    fontWeight: '700',
    color: C.white,
  },
});